services:
  db:
    container_name: postgres-development
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    restart: always
    env_file:
      - .env.local
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=secure-note
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  db-testing:
    container_name: postgres-testing
    image: postgres:16-alpine
    ports:
      - '5433:5432'
    env_file:
      - .env.local
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: secure-note-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db

volumes:
  secure-note-data:
    name: secure-note-data